# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
gem 'mysql2', '=0.4.10'
gem 'rest-client', '=2.0.2'
gem 'sequel', '=5.2.0'
gem 'telegram-bot-ruby', '=0.8.6.1'
gem 'semantic_logger', '=4.2.0'
gem 'byebug', '=10.0.0'
gem 'webrick'
